// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjwwjffiqhcmudbfrycb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqd3dqZmZpcWhjbXVkYmZyeWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzI0NTgsImV4cCI6MjA2NjI0ODQ1OH0.DlMFlbP6GWQ5uAimJ9AASP7ksUnU_2viVahpvxpSW3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);